"""Automation service — repo onboarding and workflow registry."""

from agent_backbone.services.automation._checks import (
    CheckResult,
    RepoStatus,
    _check_assume_unchanged,
    _check_git_excludes,
    _check_orch_config,
    _check_registry_entries,
    _check_sparse_checkout,
    _check_spec_dir,
    _check_symlinks_created,
    run_status_checks,
)
from agent_backbone.services.automation._pipeline import (
    _ORCH_ROOT,
    _REGISTRY_PATH,
    _REPOS_JSON,
    _SDD_INIT_SCRIPT,
    _SETUP_SCRIPT,
    _SPEC_ROOT,
    _WS_ROOT,
    OnboardingResult,
    OnboardingStep,
    RepoEntry,
    _symlink_block,
    discover_repos,
    load_repos_json,
    parse_ssh_url,
    register_repo,
    run_onboarding,
    save_repos_json,
    validate_org,
    validate_repo_name,
)
from agent_backbone.services.automation._registry import WorkflowRegistry
from agent_backbone.services.automation.exceptions import OnboardingError, WorkflowServiceError
from agent_backbone.services.automation.interface import OnboardingService
from agent_backbone.services.automation.models import WorkflowEntry

__all__ = [
    "CheckResult",
    "OnboardingError",
    "OnboardingResult",
    "OnboardingService",
    "OnboardingStep",
    "RepoEntry",
    "RepoStatus",
    "WorkflowEntry",
    "WorkflowRegistry",
    "WorkflowServiceError",
    "_ORCH_ROOT",
    "_REGISTRY_PATH",
    "_REPOS_JSON",
    "_SDD_INIT_SCRIPT",
    "_SETUP_SCRIPT",
    "_SPEC_ROOT",
    "_WS_ROOT",
    "_check_assume_unchanged",
    "_check_git_excludes",
    "_check_orch_config",
    "_check_registry_entries",
    "_check_sparse_checkout",
    "_check_spec_dir",
    "_check_symlinks_created",
    "_symlink_block",
    "discover_repos",
    "load_repos_json",
    "parse_ssh_url",
    "register_repo",
    "run_onboarding",
    "run_status_checks",
    "save_repos_json",
    "validate_org",
    "validate_repo_name",
]
