"""initial schema

Revision ID: 5844fa78a13f
Revises:
Create Date: 2026-09-01 11:01:58.457658
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5844fa78a13f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "acknowledgments",
        sa.Column("repo", sa.Text(), server_default="", nullable=False),
        sa.Column("issue_number", sa.Integer(), nullable=False),
        sa.Column("target_entity", sa.Text(), nullable=False),
        sa.Column("acknowledged_at", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint(
            "repo", "issue_number", "target_entity", name=op.f("pk_acknowledgments")
        ),
    )
    op.create_table(
        "agent_states",
        sa.Column("session_name", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), server_default="unknown", nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("current_issue", sa.Integer(), nullable=True),
        sa.Column("current_repo", sa.Text(), nullable=True),
        sa.Column("started_at", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.Column("ts", sa.Text(), nullable=True),
        sa.Column("plan_file", sa.Text(), nullable=True),
        sa.Column("plan_title", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("session_name", name=op.f("pk_agent_states")),
    )
    op.create_table(
        "agent_watches",
        sa.Column("agent_name", sa.Text(), nullable=False),
        sa.Column("repo", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("agent_name", "repo", name=op.f("pk_agent_watches")),
    )
    op.create_table(
        "agents",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("dir", sa.Text(), nullable=False),
        sa.Column("runtime", sa.Text(), server_default="claude", nullable=False),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("repo", sa.Text(), server_default="", nullable=False),
        sa.Column("tags", sa.Text(), server_default="[]", nullable=False),
        sa.Column("env", sa.Text(), server_default="{}", nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.Column("last_started_at", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_agents")),
    )
    op.create_table(
        "deliveries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("kind", sa.Text(), server_default="issue", nullable=False),
        sa.Column("repo", sa.Text(), server_default="", nullable=False),
        sa.Column("issue_number", sa.Integer(), nullable=True),
        sa.Column("target_entity", sa.Text(), nullable=False),
        sa.Column("session_name", sa.Text(), nullable=False),
        sa.Column("outcome", sa.Text(), nullable=False),
        sa.Column("flow_name", sa.Text(), server_default="", nullable=False),
        sa.Column("flow_run_id", sa.Text(), server_default="", nullable=False),
        sa.Column("preview", sa.Text(), server_default="", nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deliveries")),
    )
    with op.batch_alter_table("deliveries", schema=None) as batch_op:
        batch_op.create_index("idx_deliveries_created", ["created_at"], unique=False)
        batch_op.create_index("idx_deliveries_entity", ["target_entity"], unique=False)
        batch_op.create_index("idx_deliveries_issue", ["repo", "issue_number"], unique=False)
        batch_op.create_index("idx_deliveries_outcome", ["outcome"], unique=False)
        batch_op.create_index(
            "uq_deliveries_active_owner",
            ["repo", "issue_number", "session_name"],
            unique=True,
            postgresql_where=sa.text(
                "kind = 'issue' AND issue_number IS NOT NULL AND outcome IN ('attempting','delivered','retried')"
            ),
            sqlite_where=sa.text(
                "kind = 'issue' AND issue_number IS NOT NULL AND outcome IN ('attempting','delivered','retried')"
            ),
        )

    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("delivery_id", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("repo", sa.Text(), server_default="", nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("issue_number", sa.Integer(), nullable=True),
        sa.Column("sender", sa.Text(), server_default="", nullable=False),
        sa.Column("summary", sa.Text(), server_default="", nullable=False),
        sa.Column("received_at", sa.Text(), nullable=False),
        sa.Column("processed_at", sa.Text(), nullable=True),
        sa.Column("outcome", sa.Text(), server_default="", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index("idx_events_received", ["received_at"], unique=False)
        batch_op.create_index("idx_events_repo", ["repo"], unique=False)
        batch_op.create_index("uq_events_delivery_id", ["delivery_id"], unique=True)

    op.create_table(
        "issue_dependencies",
        sa.Column("repo", sa.Text(), server_default="", nullable=False),
        sa.Column("parent_number", sa.Integer(), nullable=False),
        sa.Column("sub_issue_number", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint(
            "repo", "parent_number", "sub_issue_number", name=op.f("pk_issue_dependencies")
        ),
    )
    with op.batch_alter_table("issue_dependencies", schema=None) as batch_op:
        batch_op.create_index("idx_deps_sub", ["repo", "sub_issue_number"], unique=False)

    op.create_table(
        "message_queue",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_name", sa.Text(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("repo", sa.Text(), server_default="", nullable=False),
        sa.Column("issue_number", sa.Integer(), nullable=True),
        sa.Column("target_entity", sa.Text(), nullable=True),
        sa.Column("delivery_kind", sa.Text(), server_default="issue", nullable=False),
        sa.Column("flow_name", sa.Text(), server_default="", nullable=True),
        sa.Column("enqueued_at", sa.Text(), nullable=False),
        sa.Column("delivered_at", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default="pending", nullable=False),
        sa.Column("leased_at", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message_queue")),
    )
    with op.batch_alter_table("message_queue", schema=None) as batch_op:
        batch_op.create_index(
            "idx_mq_leased",
            ["leased_at"],
            unique=False,
            postgresql_where=sa.text("status = 'in_progress'"),
            sqlite_where=sa.text("status = 'in_progress'"),
        )
        batch_op.create_index("idx_mq_session", ["session_name"], unique=False)
        batch_op.create_index("idx_mq_status", ["status"], unique=False)
        batch_op.create_index(
            "uq_mq_comment_dedup",
            ["session_name", "repo", "issue_number", "content_hash"],
            unique=True,
            postgresql_where=sa.text(
                "delivery_kind = 'comment' AND status IN ('pending','in_progress') AND issue_number IS NOT NULL"
            ),
            sqlite_where=sa.text(
                "delivery_kind = 'comment' AND status IN ('pending','in_progress') AND issue_number IS NOT NULL"
            ),
        )
        batch_op.create_index(
            "uq_mq_dm_dedup",
            ["session_name", "content_hash"],
            unique=True,
            postgresql_where=sa.text(
                "delivery_kind = 'direct_message' AND status IN ('pending','in_progress')"
            ),
            sqlite_where=sa.text(
                "delivery_kind = 'direct_message' AND status IN ('pending','in_progress')"
            ),
        )
        batch_op.create_index(
            "uq_mq_issue_dedup",
            ["session_name", "repo", "issue_number"],
            unique=True,
            postgresql_where=sa.text(
                "delivery_kind = 'issue' AND status IN ('pending','in_progress') AND issue_number IS NOT NULL"
            ),
            sqlite_where=sa.text(
                "delivery_kind = 'issue' AND status IN ('pending','in_progress') AND issue_number IS NOT NULL"
            ),
        )

    op.create_table(
        "settings",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_settings")),
    )
    op.create_table(
        "swarms",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("repo", sa.Text(), nullable=False),
        sa.Column("issue_number", sa.Integer(), nullable=False),
        sa.Column("initiator", sa.Text(), server_default="", nullable=False),
        sa.Column("coordinator", sa.Text(), nullable=False),
        sa.Column("branch", sa.Text(), nullable=False),
        sa.Column("worktree_dir", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("completed_at", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_swarms")),
    )
    with op.batch_alter_table("swarms", schema=None) as batch_op:
        batch_op.create_index(
            "uq_swarms_active_issue",
            ["repo", "issue_number"],
            unique=True,
            postgresql_where=sa.text("status = 'active'"),
            sqlite_where=sa.text("status = 'active'"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("swarms", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_swarms_active_issue",
            postgresql_where=sa.text("status = 'active'"),
            sqlite_where=sa.text("status = 'active'"),
        )

    op.drop_table("swarms")
    op.drop_table("settings")
    with op.batch_alter_table("message_queue", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_mq_issue_dedup",
            postgresql_where=sa.text(
                "delivery_kind = 'issue' AND status IN ('pending','in_progress') AND issue_number IS NOT NULL"
            ),
            sqlite_where=sa.text(
                "delivery_kind = 'issue' AND status IN ('pending','in_progress') AND issue_number IS NOT NULL"
            ),
        )
        batch_op.drop_index(
            "uq_mq_dm_dedup",
            postgresql_where=sa.text(
                "delivery_kind = 'direct_message' AND status IN ('pending','in_progress')"
            ),
            sqlite_where=sa.text(
                "delivery_kind = 'direct_message' AND status IN ('pending','in_progress')"
            ),
        )
        batch_op.drop_index(
            "uq_mq_comment_dedup",
            postgresql_where=sa.text(
                "delivery_kind = 'comment' AND status IN ('pending','in_progress') AND issue_number IS NOT NULL"
            ),
            sqlite_where=sa.text(
                "delivery_kind = 'comment' AND status IN ('pending','in_progress') AND issue_number IS NOT NULL"
            ),
        )
        batch_op.drop_index("idx_mq_status")
        batch_op.drop_index("idx_mq_session")
        batch_op.drop_index(
            "idx_mq_leased",
            postgresql_where=sa.text("status = 'in_progress'"),
            sqlite_where=sa.text("status = 'in_progress'"),
        )

    op.drop_table("message_queue")
    with op.batch_alter_table("issue_dependencies", schema=None) as batch_op:
        batch_op.drop_index("idx_deps_sub")

    op.drop_table("issue_dependencies")
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index("uq_events_delivery_id")
        batch_op.drop_index("idx_events_repo")
        batch_op.drop_index("idx_events_received")

    op.drop_table("events")
    with op.batch_alter_table("deliveries", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_deliveries_active_owner",
            postgresql_where=sa.text(
                "kind = 'issue' AND issue_number IS NOT NULL AND outcome IN ('attempting','delivered','retried')"
            ),
            sqlite_where=sa.text(
                "kind = 'issue' AND issue_number IS NOT NULL AND outcome IN ('attempting','delivered','retried')"
            ),
        )
        batch_op.drop_index("idx_deliveries_outcome")
        batch_op.drop_index("idx_deliveries_issue")
        batch_op.drop_index("idx_deliveries_entity")
        batch_op.drop_index("idx_deliveries_created")

    op.drop_table("deliveries")
    op.drop_table("agents")
    op.drop_table("agent_watches")
    op.drop_table("agent_states")
    op.drop_table("acknowledgments")
    # ### end Alembic commands ###
