"""Terminal service — async tmux session operations and streaming."""

from agent_backbone.services.terminal._broker import (
    SessionBroadcast,
    StreamBroker,
    _event_to_data,
    _event_type_name,
    format_sse,
    parse_sse_frame,
)
from agent_backbone.services.terminal._control_mode import (
    ControlModeConnection,
    ControlModeManager,
    _manager,
    _unescape_output,
    parse_control_mode_line,
)
from agent_backbone.services.terminal._core import (
    capture_pane,
    get_window_size,
    resize_window,
    send_keys,
    send_message,
    session_exists,
)
from agent_backbone.services.terminal._panes import (
    close_pane,
    list_panes,
    resize_pane,
    split_pane,
    swap_panes,
)
from agent_backbone.services.terminal._pty import PtyManager, PtySession
from agent_backbone.services.terminal._sessions import (
    SESSION_FORMAT_STR,
    graceful_close,
    list_sessions,
    list_sessions_rich,
    query_format_vars,
    resolve_agent_dir,
    start_session,
    stop_session,
)
from agent_backbone.services.terminal._streaming import start_pipe_pane, stop_pipe_pane
from agent_backbone.services.terminal._windows import (
    close_window,
    create_layout,
    create_window,
    list_windows,
    rename_window,
    select_window,
    set_layout,
)
from agent_backbone.services.terminal.exceptions import StreamingServiceError, TmuxError
from agent_backbone.services.terminal.interface import StreamingService, TmuxService
from agent_backbone.services.terminal.models import (
    ConnectionState,
    ControlModeEvent,
    ExitEvent,
    LayoutChangeEvent,
    ModeChangeEvent,
    OutputEvent,
    PaneInfo,
    SessionEvent,
    WindowEvent,
    WindowInfo,
)

__all__ = [
    "ConnectionState",
    "ControlModeConnection",
    "ControlModeEvent",
    "ControlModeManager",
    "ExitEvent",
    "LayoutChangeEvent",
    "ModeChangeEvent",
    "OutputEvent",
    "PaneInfo",
    "PtyManager",
    "PtySession",
    "SESSION_FORMAT_STR",
    "SessionBroadcast",
    "SessionEvent",
    "StreamBroker",
    "StreamingService",
    "StreamingServiceError",
    "TmuxError",
    "TmuxService",
    "WindowEvent",
    "WindowInfo",
    "_event_to_data",
    "_event_type_name",
    "_manager",
    "_unescape_output",
    "capture_pane",
    "close_pane",
    "close_window",
    "create_layout",
    "create_window",
    "format_sse",
    "get_window_size",
    "graceful_close",
    "list_panes",
    "list_sessions",
    "list_sessions_rich",
    "list_windows",
    "parse_control_mode_line",
    "parse_sse_frame",
    "query_format_vars",
    "rename_window",
    "resize_pane",
    "resize_window",
    "resolve_agent_dir",
    "select_window",
    "send_keys",
    "send_message",
    "session_exists",
    "set_layout",
    "split_pane",
    "start_pipe_pane",
    "start_session",
    "stop_pipe_pane",
    "stop_session",
    "swap_panes",
]
