"""Shell completion derived from the real parser; discovery never starts services."""

from __future__ import annotations

import argparse
import fcntl
import json
import os
import shlex
import sqlite3
import sys
import time
from pathlib import Path
from urllib.parse import unquote

from agent_backbone.config import RUNTIMES, SETTINGS_DEFAULTS, bootstrap_config
from agent_backbone.fs import atomic_write_text

_SCRIPTS = {
    "bash": r"""# Generated by backbone completion bash
_backbone_complete() {
    local candidate output result word previous='' prefix='' i last mode
    local -a query=()
    COMPREPLY=()
    # Readline splits '=' and ':' into words; rejoin them for argparse without
    # changing COMP_WORDBREAKS for other commands.
    for ((i=1; i<=COMP_CWORD; i++)); do
        word=${COMP_WORDS[i]}
        last=$((${#query[@]}-1))
        if ((last >= 0)) && [[ $word == '=' || $word == ':' ||
                                  $previous == '=' || $previous == ':' ]]; then
            query[last]+=$word
        else
            query+=("$word")
        fi
        previous=$word
    done
    last=$((${#query[@]}-1))
    if ((last >= 0)); then
        prefix=${query[last]%"${COMP_WORDS[COMP_CWORD]}"}
        [[ $word == '=' || $word == ':' ]] && prefix=${query[last]}
    fi
    output=$(command backbone _complete -- "${query[@]}" 2>/dev/null) && result=0 || result=$?
    if [[ $result == 2 || $result == 3 ]]; then
        word=${query[last]#*=}
        mode=-d
        [[ $result == 3 ]] && mode=-f
        while IFS= read -r candidate; do
            [[ -d $candidate ]] && candidate+=/
            COMPREPLY+=("$candidate")
        done < <(compgen "$mode" -- "$word")
        compopt -o filenames 2>/dev/null || true
    elif [[ $result == 0 && -n $output ]]; then
        while IFS= read -r candidate; do COMPREPLY+=("${candidate#"$prefix"}"); done <<< "$output"
    fi
}
complete -F _backbone_complete backbone ab
""",
    "zsh": r"""# Generated by backbone completion zsh
if (( ! $+functions[compdef] )); then
    autoload -Uz compinit
    compinit
fi
_backbone_complete() {
    local -a candidates positional
    local output result
    output=$(command backbone _complete -- "${words[@]:1:$((CURRENT-1))}" 2>/dev/null) &&
        result=0 || result=$?
    if (( result == 2 || result == 3 )); then
        [[ $PREFIX == *=* ]] && compset -P '*='
        if (( result == 2 )); then _files -/; else _files; fi
        return
    fi
    (( result == 0 )) && [[ -n $output ]] || return 1
    candidates=("${(@f)output}")
    # Inline hints prefer command/name matches to flags at an empty word.
    if (( ${BACKBONE_COMPLETION_SUGGEST:-0} )) && [[ -z $PREFIX ]]; then
        positional=("${(@)candidates:#-*}")
        (( ${#positional} )) && candidates=("${positional[@]}")
    fi
    compadd -- "${candidates[@]}"
    # Show ambiguous choices on the first Tab, even after a common prefix.
    (( compstate[nmatches] > 1 )) && compstate[list]=list
    return 0
}
compdef _backbone_complete backbone ab
""",
    "fish": r"""# Generated by backbone completion fish
function __backbone_complete
    set -l words (commandline -opc)
    set -e words[1]
    set -l token (commandline -ct)
    set -l candidates (command backbone _complete -- $words "$token" 2>/dev/null)
    set -l result $status
    if test $result -eq 2; or test $result -eq 3
        set -l prefix (string match -r '^.*=' -- "$token")
        set -l path (string replace -r '^.*=' '' -- "$token")
        set -l complete_path __fish_complete_directories
        test $result -eq 3; and set complete_path __fish_complete_path
        for candidate in ($complete_path "$path")
            printf '%s%s\n' "$prefix" "$candidate"
        end
    else if test $result -eq 0; and test (count $candidates) -gt 0
        printf '%s\n' $candidates
    end
end
complete -c backbone -f -a '(__backbone_complete)'
complete -c ab -f -a '(__backbone_complete)'
""",
}

_ZSH_SUGGESTIONS = r"""
# Uses an already installed zsh-autosuggestions plugin; other commands keep
# their existing strategies. Right arrow accepts the hint without executing it.
_zsh_autosuggest_strategy_backbone() {
    [[ $1 == (backbone|ab)' '* ]] || return 1
    (( $+functions[_zsh_autosuggest_strategy_completion] )) || return 1
    local BACKBONE_COMPLETION_SUGGEST=1
    _zsh_autosuggest_strategy_completion "$1"
}
typeset -ga ZSH_AUTOSUGGEST_STRATEGY
(( ${#ZSH_AUTOSUGGEST_STRATEGY} )) || ZSH_AUTOSUGGEST_STRATEGY=(history)
if (( ! ${ZSH_AUTOSUGGEST_STRATEGY[(Ie)backbone]} )); then
    ZSH_AUTOSUGGEST_STRATEGY+=(backbone)
fi
"""
_START = "# >>> agent-backbone completion >>>"
_END = "# <<< agent-backbone completion <<<"


def _rc_path(shell: str) -> Path:
    if shell == "zsh":
        return Path(os.environ.get("ZDOTDIR") or Path.home()) / ".zshrc"
    if shell == "bash":
        return Path.home() / ".bashrc"
    root = Path(os.environ.get("XDG_CONFIG_HOME") or Path.home() / ".config")
    return root / "fish" / "conf.d" / "agent-backbone-completion.fish"


def _install(
    shell: str, path: Path, *, suggestions: bool, remove: bool
) -> tuple[bool, Path | None]:
    """Replace only our marked block, backing up existing content before editing."""
    # Preserve a dotfile symlink and edit its target, as a dotfile manager expects.
    path = path.expanduser().resolve()
    path.parent.mkdir(parents=True, exist_ok=True)
    # Lock a stable sidecar: atomic replacement changes the rc file's inode.
    # Keep the lock file so waiting installers never lock a different inode.
    lock_path = path.with_name(path.name + ".backbone-completion.lock")
    fd = os.open(lock_path, os.O_CREAT | os.O_RDWR | os.O_NOFOLLOW, 0o600)
    with os.fdopen(fd, "a") as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        return _install_locked(shell, path, suggestions=suggestions, remove=remove)


def _install_locked(
    shell: str, path: Path, *, suggestions: bool, remove: bool
) -> tuple[bool, Path | None]:
    before = path.read_text() if path.exists() else ""
    if before.count(_START) != before.count(_END) or before.count(_START) > 1:
        raise ValueError(f"incomplete or duplicate completion markers in {path}; repair them first")
    start, end = before.find(_START), before.find(_END)
    if start >= 0 and end < start:
        raise ValueError(f"reversed completion markers in {path}; repair them first")
    command = f"backbone completion {shell}" + (" --suggestions" if suggestions else "")
    if shell == "fish":
        body = (
            "if status is-interactive; and command -sq backbone\n"
            f"    command {command} | source\nend"
        )
    else:
        body = f"if command -v backbone >/dev/null 2>&1; then\n    source <(command {command})\nfi"
    block = f"{_START}\n{body}\n{_END}"
    if start >= 0:
        tail = end + len(_END)
        if remove and before[tail : tail + 1] == "\n":
            tail += 1
        after = before[:start] + ("" if remove else block) + before[tail:]
    elif remove:
        return False, None
    else:
        after = before + ("\n" if before and not before.endswith("\n") else "") + block + "\n"
    if after == before:
        return False, None
    backup = None
    if before:
        backup = path.with_name(f"{path.name}.backbone-backup-{time.time_ns()}")
        atomic_write_text(backup, before)
    # Avoid overwriting a concurrent edit made while the backup was written.
    if (path.read_text() if path.exists() else "") != before:
        raise ValueError(f"{path} changed during setup; nothing was overwritten")
    atomic_write_text(path, after)
    return True, backup


def cmd_completion(args: argparse.Namespace) -> int:
    if args.suggestions and args.shell != "zsh":
        print(
            "--suggestions integrates zsh-autosuggestions; Fish has native suggestions",
            file=sys.stderr,
        )
        return 1
    if args.rc_file and not (args.install or args.uninstall):
        print("--rc-file requires --install or --uninstall", file=sys.stderr)
        return 1
    if not (args.install or args.uninstall):
        print(_SCRIPTS[args.shell] + (_ZSH_SUGGESTIONS if args.suggestions else ""), end="")
        return 0
    path = (Path(args.rc_file) if args.rc_file else _rc_path(args.shell)).expanduser()
    try:
        changed, backup = _install(
            args.shell, path, suggestions=args.suggestions, remove=args.uninstall
        )
    except (OSError, ValueError) as exc:
        print(f"completion: {exc}", file=sys.stderr)
        return 1
    if args.uninstall:
        print(f"{'Removed completion from' if changed else 'No managed completion in'} {path}")
        print("Open a new shell to finish unloading it.")
    else:
        print(
            f"{'Installed completion in' if changed else 'Completion already configured in'} {path}"
        )
        print("Open a new terminal, or enable it here:")
        command = f"backbone completion {args.shell}" + (
            " --suggestions" if args.suggestions else ""
        )
        print(f"  {command} | source" if args.shell == "fish" else f"  source <({command})")
        if args.suggestions:
            print(
                "Inline hints require zsh-autosuggestions to be loaded; Right arrow accepts a hint."
            )
    if backup:
        print(f"Backup: {shlex.quote(str(backup))}")
    return 0


def _catalog() -> dict[str, list[str]]:
    """Read only names from a local SQLite database, even while the server is down.

    Do not use Direct: opening the service can create/migrate a database. A short
    read-only connection also avoids waiting for the API or a provider on Tab.
    Non-SQLite installations still have command/option/path completion.
    """
    result: dict[str, list[str]] = {"agents": [], "swarms": [], "tags": []}
    config = bootstrap_config()
    prefix = "sqlite+aiosqlite:///"
    if not config.database_url.startswith(prefix):
        return result
    path = Path(unquote(config.database_url.removeprefix(prefix))).expanduser().resolve()
    try:
        with sqlite3.connect(path.as_uri() + "?mode=ro", uri=True, timeout=0.05) as conn:
            for name, raw_tags in conn.execute("SELECT name, tags FROM agents"):
                result["agents"].append(name)
                tags = json.loads(raw_tags)
                if isinstance(tags, list):
                    result["tags"].extend(tag for tag in tags if isinstance(tag, str))
            result["swarms"] = [r[0] for r in conn.execute("SELECT name FROM swarms")]
    except (OSError, sqlite3.Error, ValueError, TypeError):
        pass
    return result


def _values(action: argparse.Action, context: list[str]) -> list[str]:
    if action.choices is not None:
        return [str(value) for value in action.choices]
    dest = action.dest
    if dest == "runtime":
        return list(RUNTIMES)
    if dest == "key" and context[:1] == ["config"]:
        return list(SETTINGS_DEFAULTS)
    if dest in ("topic", "page"):
        from agent_backbone.help import list_docs, list_topics

        items = list_docs() if dest == "page" else list_topics(bootstrap_config().data_dir)
        return [item["name"] for item in items]
    if context[:1] in (["templates"], ["instructions"]) and dest in ("name", "names", "policies"):
        from agent_backbone.templates import list_templates

        entries = list_templates(bootstrap_config().data_dir)
        if dest == "policies":
            return [
                row["name"].removeprefix("policy:")
                for row in entries
                if row["name"].startswith("policy:")
            ]
        return [row["name"] for row in entries]
    if dest == "assignments":
        return [
            key + "="
            for key in (
                "runtime",
                "model",
                "dir",
                "repo",
                "description",
                "always_on",
                "unattended",
                "tags",
            )
        ]
    if dest in ("tag", "tags"):
        return _catalog()["tags"]
    if context == ["swarm", "create"] and dest == "name":
        return []
    if dest == "swarm" or (context[:1] == ["swarm"] and dest == "name"):
        return _catalog()["swarms"]
    if dest in ("name", "names", "agent", "initiator", "targets"):
        catalog = _catalog()
        return catalog["agents"] + (catalog["swarms"] if context == ["tell"] else [])
    return []


def _candidates(parser: argparse.ArgumentParser, words: list[str]) -> tuple[list[str], int]:
    """Walk complete words without parse_args (no exits, help text or side effects)."""
    if words[:1] == ["help"]:
        if len(words) > 2:
            return _candidates(parser, words[1:])
        from agent_backbone.help import list_topics

        prefix = words[1] if len(words) == 2 else ""
        topics = [
            t["name"]
            for t in list_topics(bootstrap_config().data_dir)
            if t["name"].startswith(prefix)
        ]
        return sorted(set(topics + candidates(parser, [prefix]))), 0
    previous, current = (words[:-1], words[-1]) if words else ([], "")
    context: list[str] = []
    position = 0
    pending: argparse.Action | None = None
    options = True
    used: set[str] = set()
    for word in previous:
        if pending is not None:
            pending = None
            continue
        if word == "--":
            options = False
            continue
        flag = word.split("=", 1)[0]
        if options and flag in parser._option_string_actions:
            action = parser._option_string_actions[flag]
            if not isinstance(action, argparse._AppendAction):
                used.update(action.option_strings)
            if action.nargs != 0 and "=" not in word:
                pending = action
            continue
        actions = [a for a in parser._actions if not a.option_strings]
        if position >= len(actions):
            continue
        action = actions[position]
        if isinstance(action, argparse._SubParsersAction):
            if word not in action.choices:
                return [], 0
            parser = action.choices[word]
            context.append(word)
            position = 0
            used.clear()
        elif action.nargs not in ("*", "+", argparse.REMAINDER):
            position += 1
    prefix = ""
    if options and current.startswith("--") and "=" in current:
        flag, current = current.split("=", 1)
        pending = parser._option_string_actions.get(flag)
        if pending is None or pending.nargs == 0:
            return [], 0
        prefix = flag + "="
    path_completion = 0  # Shell protocol: 2 = directories, 3 = files, 0 = candidates only.
    if pending is not None:
        values = _values(pending, context)
        if pending.dest in ("dir", "data_dir"):
            path_completion = 2
        elif pending.dest in ("rc_file", "file"):
            path_completion = 3
    elif options and current.startswith("-"):
        values = [v for v in parser._option_string_actions if v not in used]
    else:
        actions = [a for a in parser._actions if not a.option_strings]
        action = actions[position] if position < len(actions) else None
        values = _values(action, context) if action else []
        if action and action.dest == "assignments" and "=" in current:
            key, current = current.split("=", 1)
            prefix = key + "="
            values = (
                list(RUNTIMES)
                if key == "runtime"
                else (["true", "false"] if key in ("always_on", "unattended") else [])
            )
            path_completion = 2 if key == "dir" else 0
        elif options and not current:
            values += [v for v in parser._option_string_actions if v not in used]
    return sorted(
        {
            prefix + value
            for value in values
            if value.startswith(current) and all(c.isprintable() for c in value)
        }
    ), path_completion


def candidates(parser: argparse.ArgumentParser, words: list[str]) -> list[str]:
    return _candidates(parser, words)[0]


def complete(parser: argparse.ArgumentParser, words: list[str]) -> int:
    values, path_completion = _candidates(parser, words)
    for value in values:
        print(value)
    return path_completion
